import type { Metadata } from "next";
import "./globals.css";
import bg from "../assets/bg.png";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className="text-white h-screen"
        style={{
          backgroundImage: `url(${bg.src})`,
          backgroundSize: "cover",
          backgroundPosition: "center",
        
        }}
      >
        {children}
      </body>
    </html>
  );
}
