import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "SignUp",
  description: "Generated by create next app",
};

export default function Layout({ children }: { children: React.ReactNode }) {
  return (
    <div className="w-full h-screen">
      {children}
    </div>
  )
}
